# Generated by Django 4.1.13 on 2025-12-29 09:11

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=orders.models.generate_order_id, editable=False, max_length=20, unique=True),
        ),
    ]
