# Generated by Django 5.2.9 on 2026-01-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_gift_card_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.CharField(max_length=50),
        ),
    ]
