# Generated by Django 5.2.9 on 2026-01-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Anonymous session ID for non-logged in users', max_length=255, null=True)),
                ('interaction_type', models.CharField(choices=[('VIEW', 'View Product'), ('HOVER', 'Hover Product'), ('SEARCH', 'Search Query'), ('CART_ADD', 'Add to Cart'), ('PURCHASE', 'Purchase')], max_length=20)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_fa50e1_idx'), models.Index(fields=['session_id', 'timestamp'], name='analytics_u_session_16bf17_idx'), models.Index(fields=['interaction_type'], name='analytics_u_interac_b98494_idx')],
            },
        ),
    ]
