# Generated by Django 4.1.13 on 2026-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('VIEW', 'View Product'), ('HOVER', 'Hover Product'), ('SEARCH', 'Search Query'), ('CART_ADD', 'Add to Cart'), ('PURCHASE', 'Purchase'), ('TIME_30S', 'Dwell Time > 30s'), ('DEEP_SCROLL', 'Deep Scroll > 60%')], max_length=20),
        ),
    ]
